/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as InstallIndexRouteImport } from './routes/install/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin/users'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin/settings'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin/schools'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalBillingRouteImport } from './routes/portal/billing'
import { Route as PortalApplyRouteImport } from './routes/portal/apply'
import { Route as PortalApplicationsRouteImport } from './routes/portal/applications'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as DemoFamilyRouteImport } from './routes/demo/family'
import { Route as DemoAdminRouteImport } from './routes/demo/admin'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminFamiliesRouteImport } from './routes/admin/families'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as SuperAdminSchoolsNewRouteImport } from './routes/super-admin/schools/new'
import { Route as SuperAdminSchoolsIdRouteImport } from './routes/super-admin/schools/$id'
import { Route as AdminLeadsNewRouteImport } from './routes/admin/leads/new'
import { Route as AdminLeadsIdRouteImport } from './routes/admin/leads/$id'
import { Route as AdminFamiliesNewRouteImport } from './routes/admin/families/new'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin/applications/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/install/',
  path: '/install/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/super-admin/settings',
  path: '/super-admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({
  id: '/super-admin/schools',
  path: '/super-admin/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/portal/billing',
  path: '/portal/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalApplyRoute = PortalApplyRouteImport.update({
  id: '/portal/apply',
  path: '/portal/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalApplicationsRoute = PortalApplicationsRouteImport.update({
  id: '/portal/applications',
  path: '/portal/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFamilyRoute = DemoFamilyRouteImport.update({
  id: '/demo/family',
  path: '/demo/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/demo/admin',
  path: '/demo/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFamiliesRoute = AdminFamiliesRouteImport.update({
  id: '/admin/families',
  path: '/admin/families',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSchoolsNewRoute = SuperAdminSchoolsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SuperAdminSchoolsRoute,
} as any)
const SuperAdminSchoolsIdRoute = SuperAdminSchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuperAdminSchoolsRoute,
} as any)
const AdminLeadsNewRoute = AdminLeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminFamiliesNewRoute = AdminFamiliesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFamiliesRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/families': typeof AdminFamiliesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/team': typeof AdminTeamRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/family': typeof DemoFamilyRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/apply': typeof PortalApplyRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/install/': typeof InstallIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/families/new': typeof AdminFamiliesNewRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/super-admin/schools/$id': typeof SuperAdminSchoolsIdRoute
  '/super-admin/schools/new': typeof SuperAdminSchoolsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/families': typeof AdminFamiliesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/team': typeof AdminTeamRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/family': typeof DemoFamilyRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/apply': typeof PortalApplyRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/install': typeof InstallIndexRoute
  '/portal': typeof PortalIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/families/new': typeof AdminFamiliesNewRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/super-admin/schools/$id': typeof SuperAdminSchoolsIdRoute
  '/super-admin/schools/new': typeof SuperAdminSchoolsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/families': typeof AdminFamiliesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/team': typeof AdminTeamRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/family': typeof DemoFamilyRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/apply': typeof PortalApplyRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/install/': typeof InstallIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/families/new': typeof AdminFamiliesNewRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/super-admin/schools/$id': typeof SuperAdminSchoolsIdRoute
  '/super-admin/schools/new': typeof SuperAdminSchoolsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/admin/applications'
    | '/admin/families'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/demo/admin'
    | '/demo/family'
    | '/invite/accept'
    | '/portal/applications'
    | '/portal/apply'
    | '/portal/billing'
    | '/portal/settings'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin/'
    | '/install/'
    | '/portal/'
    | '/super-admin/'
    | '/admin/applications/$id'
    | '/admin/families/new'
    | '/admin/leads/$id'
    | '/admin/leads/new'
    | '/super-admin/schools/$id'
    | '/super-admin/schools/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/admin/applications'
    | '/admin/families'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/demo/admin'
    | '/demo/family'
    | '/invite/accept'
    | '/portal/applications'
    | '/portal/apply'
    | '/portal/billing'
    | '/portal/settings'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin'
    | '/install'
    | '/portal'
    | '/super-admin'
    | '/admin/applications/$id'
    | '/admin/families/new'
    | '/admin/leads/$id'
    | '/admin/leads/new'
    | '/super-admin/schools/$id'
    | '/super-admin/schools/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/admin/applications'
    | '/admin/families'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/demo/admin'
    | '/demo/family'
    | '/invite/accept'
    | '/portal/applications'
    | '/portal/apply'
    | '/portal/billing'
    | '/portal/settings'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin/'
    | '/install/'
    | '/portal/'
    | '/super-admin/'
    | '/admin/applications/$id'
    | '/admin/families/new'
    | '/admin/leads/$id'
    | '/admin/leads/new'
    | '/super-admin/schools/$id'
    | '/super-admin/schools/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminFamiliesRoute: typeof AdminFamiliesRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  DemoAdminRoute: typeof DemoAdminRoute
  DemoFamilyRoute: typeof DemoFamilyRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  PortalApplicationsRoute: typeof PortalApplicationsRoute
  PortalApplyRoute: typeof PortalApplyRoute
  PortalBillingRoute: typeof PortalBillingRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  SuperAdminSchoolsRoute: typeof SuperAdminSchoolsRouteWithChildren
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InstallIndexRoute: typeof InstallIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/': {
      id: '/install/'
      path: '/install'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/schools': {
      id: '/super-admin/schools'
      path: '/super-admin/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof SuperAdminSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/portal/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/apply': {
      id: '/portal/apply'
      path: '/portal/apply'
      fullPath: '/portal/apply'
      preLoaderRoute: typeof PortalApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/applications': {
      id: '/portal/applications'
      path: '/portal/applications'
      fullPath: '/portal/applications'
      preLoaderRoute: typeof PortalApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/family': {
      id: '/demo/family'
      path: '/demo/family'
      fullPath: '/demo/family'
      preLoaderRoute: typeof DemoFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/admin': {
      id: '/demo/admin'
      path: '/demo/admin'
      fullPath: '/demo/admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/families': {
      id: '/admin/families'
      path: '/admin/families'
      fullPath: '/admin/families'
      preLoaderRoute: typeof AdminFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/schools/new': {
      id: '/super-admin/schools/new'
      path: '/new'
      fullPath: '/super-admin/schools/new'
      preLoaderRoute: typeof SuperAdminSchoolsNewRouteImport
      parentRoute: typeof SuperAdminSchoolsRoute
    }
    '/super-admin/schools/$id': {
      id: '/super-admin/schools/$id'
      path: '/$id'
      fullPath: '/super-admin/schools/$id'
      preLoaderRoute: typeof SuperAdminSchoolsIdRouteImport
      parentRoute: typeof SuperAdminSchoolsRoute
    }
    '/admin/leads/new': {
      id: '/admin/leads/new'
      path: '/new'
      fullPath: '/admin/leads/new'
      preLoaderRoute: typeof AdminLeadsNewRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/families/new': {
      id: '/admin/families/new'
      path: '/new'
      fullPath: '/admin/families/new'
      preLoaderRoute: typeof AdminFamiliesNewRouteImport
      parentRoute: typeof AdminFamiliesRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
  }
}

interface AdminApplicationsRouteChildren {
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminFamiliesRouteChildren {
  AdminFamiliesNewRoute: typeof AdminFamiliesNewRoute
}

const AdminFamiliesRouteChildren: AdminFamiliesRouteChildren = {
  AdminFamiliesNewRoute: AdminFamiliesNewRoute,
}

const AdminFamiliesRouteWithChildren = AdminFamiliesRoute._addFileChildren(
  AdminFamiliesRouteChildren,
)

interface AdminLeadsRouteChildren {
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
  AdminLeadsNewRoute: typeof AdminLeadsNewRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsIdRoute: AdminLeadsIdRoute,
  AdminLeadsNewRoute: AdminLeadsNewRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface SuperAdminSchoolsRouteChildren {
  SuperAdminSchoolsIdRoute: typeof SuperAdminSchoolsIdRoute
  SuperAdminSchoolsNewRoute: typeof SuperAdminSchoolsNewRoute
}

const SuperAdminSchoolsRouteChildren: SuperAdminSchoolsRouteChildren = {
  SuperAdminSchoolsIdRoute: SuperAdminSchoolsIdRoute,
  SuperAdminSchoolsNewRoute: SuperAdminSchoolsNewRoute,
}

const SuperAdminSchoolsRouteWithChildren =
  SuperAdminSchoolsRoute._addFileChildren(SuperAdminSchoolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminFamiliesRoute: AdminFamiliesRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeamRoute: AdminTeamRoute,
  DemoAdminRoute: DemoAdminRoute,
  DemoFamilyRoute: DemoFamilyRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  PortalApplicationsRoute: PortalApplicationsRoute,
  PortalApplyRoute: PortalApplyRoute,
  PortalBillingRoute: PortalBillingRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  SuperAdminSchoolsRoute: SuperAdminSchoolsRouteWithChildren,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  InstallIndexRoute: InstallIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
